export const pricingPlans = [
  {
    title: "Landing Page",
    price: "Rp 699K",
    subtitle: "one-time",
    idealFor: "Solusi website landing page profesional untuk bisnis Anda",
    features: [
      "Desain Modern & Responsif",
      "Optimasi SEO On-Page",
      "Form Contact & WhatsApp",
      "Integrasi Google Analytics",
      "Integrasi Social Media",
      "SSL Security (HTTPS)",
      "Speed Optimization",
      "Free Domain .com",
    ],
  },
  {
    title: "Company Profile",
    price: "Rp 1.999K",
    subtitle: "one-time",
    idealFor: "Website company profile lengkap untuk perusahaan",
    features: [
      "Desain Premium & Responsif",
      "Full SEO Optimization",
      "CMS Admin Panel",
      "Blog/News System",
      "Form Contact & WhatsApp",
      "Google Maps Integration",
      "Google Analytics & Search Console",
      "Social Media Integration",
    ],
    highlighted: true,
    badge: "MOST POPULAR",
  },
  {
    title: "Custom Website",
    price: "Rp 2.999K",
    subtitle: "starts from",
    idealFor: "Solusi website custom sesuai kebutuhan bisnis Anda",
    features: [
      "Analisa Kebutuhan Bisnis",
      "Custom Design Premium",
      "Custom Development",
      "Database Design",
      "API Integration",
      "Payment Gateway",
      "Advanced Security",
      "High Performance Setup",
    ],
  },
];
