import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Geist_Mono, Sora } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbars/Navbar";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sora = Sora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-sora",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.className} ${geistMono.variable} antialiased bg-[#070815] text-[#f5f6ff]`}
      >
        <div>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
